### PR TITLE
fix: component id 0 not being de-selected

### LINKED ISSUE #127: First component selection is persisted
The GIF uses a nested component structure but the same problem occurs with non-nested components.
Dec-15-2020 21-10-11

I'm guessing the previous selection state isn't being cleared, only if it's the first selection. Haven't dived into the problem but will have a look now.

### PR DESCRIPTION
**Pull request by ryangjchandler**
Closes #127.

Problem seems to be `0` being considered falsy, so just checking if it's truthy or equal to `0` is the simplest solution. Open to more solutions too.

### CODE REVIEW

**Review by HugoDF — APPROVED** [review]

**Comment by HugoDF** [comment]
Maybe we can start the counter at 1?

**Comment by ryangjchandler** [comment]
> Maybe we can start the counter at 1?

Yeah, that could work as well.

**Comment by HugoDF** [comment]
> > Maybe we can start the counter at 1?
> 
> Yeah, that could work as well.

Edited my comment, the code used to do a pre-increment so essentially started at 1

**Comment by HugoDF** [comment]
Should we add a "components can be unselected" test/assertion?

**Comment by ryangjchandler** [comment]
I've just made it start from 1 instead of messing pre-increment. Can change it to that if you want though.

Might be worth adding a test for de-selecting yeah.

**Pull request merged**
