### PR TITLE
Small style changes to warnings tab and footer status messages

### PR DESCRIPTION
**Pull request by stephenoldham**
Tests have been updated to allow for differences in the UI. Also may have snook in a little change to the funding yaml...💰👀😉

### CODE REVIEW

**Comment by stephenoldham** [comment]
Any thoughts @HugoDF?

**Comment by HugoDF** [comment]
Haven't had a chance to have a look, will let you know 🙂

**Comment by stephenoldham** [comment]
> Haven't had a chance to have a look, will let you know 🙂

Ah no problem fella 👍🏼

**Comment by HugoDF** [comment]
Really nice touches 👍 

Screenshot 2021-01-28 at 20 45 57

**Pull request merged**
