### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by KevinBatdorf**
Just being a little picky here but figured we could update some of the readme in one go for some clarity and consistency. I likely missed some things too so feel free to update this PR, or comment.

Some things to note:

1. We should probably always use `Alpine.js devtools` exactly just for consistency when referring to the devtools, but could more loosely say ".... an Alpine component", etc
2. Lowercase on devtools simply because Vue does it, and why not.
3. We should probably differentiate the case when talking about Chrome/FF DevTools which uses that specific case. I'm not sure why they capitalize it like that. I thought maybe a branding thing, but maybe not. But having a different case helps differentiate if needed.

### CODE REVIEW

**Comment by HugoDF** [comment]
Dunno about `devtools` vs `Devtools` vs `DevTools` I don't think anyone actually notices the casing, in the majority of cases all 3 are considered the same.

For context:
- React uses "Developer Tools" https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
- Vue does use "devtools" https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd
- Svelte uses "Devtools" https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn
- Augury (Angular) uses "Dev Tools" https://augury.rangle.io/ 🙈 

1 & 2 I think it's fine to do `devtools` (FF/Chrome web extension store listings use them in the title, should update the description).

Not really too bothered about 3 since I don't think anyone notices the casing.

**Comment by KevinBatdorf** [comment]
Sounds good. I think you have to update the description from the account page. 

> I don't think anyone notices the casing

::faints:: just kidding, it doesn't bother me too much except I think we should aim to be consistent.

**Comment by HugoDF** [comment]
> Sounds good. I think you have to update the description from the account page.
> 
> > I don't think anyone notices the casing
> 
> ::faints:: just kidding, it doesn't bother me too much except I think we should aim to be consistent.

Cool, will do as soon as we merge this one, I think you've ended up with a merge conflict.

**Comment by HugoDF** [comment]
Dunno that the following are actually inaccurate 😄 

https://github.com/alpine-collective/alpinejs-devtools/blob/master/package.json#L5

https://github.com/alpine-collective/alpinejs-devtools/blob/master/packages/shell-chrome/assets/manifest.json#L3

**Comment by KevinBatdorf** [comment]
I would say those are accurate as they are referring to the Chrome/FF entire DevTools window and not specifically to our single devtools tab 😆 

(essentially my #3 comment anyway)

**Comment by KevinBatdorf** [comment]
Merge conflict should be resolved now if you want to check that part

**Review by HugoDF — APPROVED** [review]

**Pull request merged**
