### PR TITLE
Fix crash on backend.js re-injection

### PR DESCRIPTION
**Pull request by HugoDF**
Example reproduction steps: open panel, close devtools and re-open them.

Using `let` in the top-level scope of `backend.js` causes runtime issues if backend.js gets injected multiple times.

Not sure how to test for this, maybe concatenate backend.js with itself and check there are no syntax errors?

### CODE REVIEW

**Review by ryangjchandler — APPROVED** [review]
Can't see any problems with this approach, testing it is a PITA though..

**Comment by HugoDF** [comment]
> Can't see any problems with this approach, testing it is a PITA though..

Yep

Re-injecting the script in the simulator didn't do it so I left it haha

**Comment by KevinBatdorf** [comment]
Maybe we can set up a dev workflow where we have both the simulator open as well as a page with the actual devtools open, both with auto reload or something.

**Comment by HugoDF** [comment]
> Maybe we can set up a dev workflow where we have both the simulator open as well as a page with the actual devtools open, both with auto reload or something. 

Yeah that might be possible. When looking at https://github.com/alpine-collective/alpinejs-devtools/issues/63 I saw that other extensions have something like that set up with a package, even Vue devtools has that I think.


I think now that everything is stored on `window.__alpineDevtool` any additions/modifications will follow the pattern so we should be good, just something to bear in mind during reviews/manual testing.

**Pull request merged**
